//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_Winform
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangCongChiTiet
    {
        public int ID { get; set; }
        public string MaKC { get; set; }
        public string MaNV { get; set; }
        public string TenNV { get; set; }
        public Nullable<System.DateTime> ngay { get; set; }
        public string thu { get; set; }
        public string giovao { get; set; }
        public Nullable<int> ngaycong { get; set; }
        public Nullable<int> ngayphep { get; set; }
        public string kyhieu { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
